const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('index.html','utf8');
const block=(a,b)=>html.slice(html.indexOf(a),html.indexOf(b,html.indexOf(a)+a.length));
const tick=()=>new Promise(r=>setImmediate(r));
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject};};
function context(code,extras={}){const c={console,Promise,Date,Math,JSON,setTimeout,clearTimeout,...extras};vm.createContext(c);vm.runInContext(code,c);return c;}
const responseCode=block('function apiResponse_','function api(payload)');
for(const reason of ['unknown user or password','account not approved yet'])test('explicit credential rejection: '+reason,async()=>{const c=context(responseCode);await assert.rejects(c.apiResponse_({ok:true,json:async()=>({ok:false,error:reason})}),e=>e.authInvalid===true);});
for(const reason of ['not allowed','Lock timed out','Service unavailable'])test('temporary/authorization error does not invalidate session: '+reason,async()=>{const c=context(responseCode);await assert.rejects(c.apiResponse_({ok:true,json:async()=>({ok:false,error:reason})}),e=>!e.authInvalid);});
test('HTTP error is identified as server error, not offline or invalid credentials',()=>{const c=context(responseCode);assert.throws(()=>c.apiResponse_({ok:false,status:503}),/HTTP 503/);});
test('malformed JSON envelope is not accepted',async()=>{const c=context(responseCode);await assert.rejects(c.apiResponse_({ok:true,json:async()=>({})}),/Invalid server response/);});
function bootContext(result){return context(block('function boot(){','\nopen()'),{CFG:{url:'local'},ME:{username:'A',name:'A',role:'Worker'},showHome(){},showAuth(){this.shown=true;},saveSession(){},clearSession(){this.cleared=true;return Promise.resolve();},apiGet:()=>result,document:{querySelectorAll:()=>[]},xeroStatus_(){},location:{hash:''},authMsg(){}});}
test('startup retains cached session after network failure',async()=>{const c=bootContext(Promise.reject(new Error('Failed to fetch')));c.boot();await tick();assert.ok(c.ME);assert.ok(!c.cleared);});
test('startup clears only explicitly rejected credentials',async()=>{const c=bootContext(Promise.reject(Object.assign(new Error('unknown user or password'),{authInvalid:true})));c.clearSession=()=>{c.cleared=true;return Promise.resolve();};c.boot();await tick();assert.ok(c.cleared);});
test('late startup answer cannot modify another login',async()=>{const d=deferred(),c=bootContext(d.promise);c.boot();c.ME={name:'B'};d.resolve({user:{name:'A',role:'Admin'}});await tick();assert.equal(c.ME.name,'B');});
test('late startup rejection cannot log out another account',async()=>{const d=deferred(),c=bootContext(d.promise);c.boot();c.ME={name:'B'};d.reject(Object.assign(new Error('unknown user or password'),{authInvalid:true}));await tick();assert.ok(!c.cleared);});
test('put waits for transaction commit and captures the input',async()=>{let t,written;const c=context(block('function put(store,val)','function getAll('),{MEM:false,DB:{transaction(){t={objectStore:()=>({put(v){written=v;}})};return t;}}});const row={id:'a',nested:{value:1}};let done=false;const p=c.put('jobs',row).then(()=>done=true);row.nested.value=2;await tick();assert.equal(done,false);assert.equal(written.nested.value,1);t.oncomplete();await p;assert.ok(done);});
test('transaction abort rejects save',async()=>{let t;const c=context(block('function put(store,val)','function getAll('),{MEM:false,DB:{transaction(){return t={objectStore:()=>({put(){}})};}}});const p=c.put('jobs',{id:'a'});t.onabort();await assert.rejects(p,/Local save failed/);});
function cardContext(){const nodes=new Map();const writes=[];const c=context(block('var jcRemoteChain=','function jcRenderAll_')+block('function jcSubmit_','function jcMetaOnly_'),{MEM:false,JC:{id:'a',customer:'Test',site:'Test',date:'2026-09-24',types:['custom'],sections:{photo:{img:'test-photo'}},status:'DRAFT'},ME:{username:'test'},CFG:{url:'local'},window:{},document:{getElementById(id){if(!nodes.has(id))nodes.set(id,{});return nodes.get(id);}},put:async(store,row)=>{writes.push(JSON.parse(JSON.stringify(row)));},jcMetaOnly_:x=>x,jcAcknowledge_:async()=>true,alert:m=>{throw new Error(m);}});return {c,writes,nodes};}
test('configured Supabase without session does not intercept Sheets',()=>{const {c}=cardContext();c.window.FlagshipSupabase={enabled:()=>true,getSession:()=>null};assert.equal(c.jcSupabaseEnabled_(),false);});
test('save stays bound to original card while another is opened',async()=>{const {c,writes}=cardContext();const d=deferred();c.put=async(s,row)=>{await d.promise;writes.push(row);};const p=c.jcSaveLocal_();c.JC={id:'b'};d.resolve();await p;assert.equal(writes[0].id,'a');assert.equal(writes[0].sections.photo.img,'test-photo');});
test('failed local save prevents Job Card submission',async()=>{const {c}=cardContext();let requests=0;c.put=async()=>{throw new Error('Quota exceeded');};c.api=async()=>{requests++;};await c.jcSubmit_();assert.equal(requests,0);assert.equal(c.JC.status,'DRAFT');});
test('rejected Job Card stays draft with reason',async()=>{const {c,nodes}=cardContext();c.api=async()=>{throw new Error('Not allowed');};await c.jcSubmit_();assert.equal(c.JC.status,'DRAFT');assert.match(nodes.get('jcMsg').textContent,/Not allowed/);});
test('success envelope without exact card acknowledgement stays draft',async()=>{const {c}=cardContext();c.api=async()=>({ok:true,id:'different',status:'SUBMITTED'});await c.jcSubmit_();assert.equal(c.JC.status,'DRAFT');});
test('matching acknowledgement accepts submitted card',async()=>{const {c}=cardContext();c.api=async()=>({ok:true,id:'a',status:'SUBMITTED'});await c.jcSubmit_();assert.equal(c.JC.status,'SUBMITTED');});
test('older Job Card response does not accept newer edits',async()=>{const {c}=cardContext(),d=deferred();c.api=()=>d.promise;const p=c.jcSubmit_();await tick();c.JC.customer='Edited';await c.jcScheduleSave_();d.resolve({ok:true,id:'a',status:'SUBMITTED'});await p;assert.equal(c.JC.status,'DRAFT');assert.equal(c.JC.customer,'Edited');});
test('duplicate submit clicks issue one request',async()=>{const {c}=cardContext(),d=deferred();let requests=0;c.api=()=>{requests++;return d.promise;};const p=c.jcSubmit_();await tick();await c.jcSubmit_();assert.equal(requests,1);d.resolve({id:'a',status:'SUBMITTED'});await p;});
test('remote autosaves are serialized, not last-network-response wins',async()=>{const {c}=cardContext(),d=deferred(),calls=[],session={};c.window.FlagshipSupabase={enabled:()=>true,getSession:()=>session,saveJobCard:async card=>{calls.push(card.id);if(card.id==='first')await d.promise;return card;}};const a=c.jcSync_({id:'first'}),b=c.jcSync_({id:'second'});await tick();assert.deepEqual(calls,['first']);d.resolve();await Promise.all([a,b]);assert.deepEqual(calls,['first','second']);});
test('queued remote save is not replayed under a different account',async()=>{const {c}=cardContext(),d=deferred(),session={};let calls=0;c.window.FlagshipSupabase={enabled:()=>true,getSession:()=>session,saveJobCard:async()=>{calls++;await d.promise;}};const a=c.jcSync_({id:'a'});await tick();const b=c.jcSync_({id:'b'});c.ME={username:'other'};const rejected=assert.rejects(b,/Session changed/);d.resolve();await a;await rejected;assert.equal(calls,1);});
for(const name of ['save','vpSave'])test(name+' captures document before navigation without delayed writes',async()=>{const writes=[],c=context(name==='save'?block('function save(){',"document.addEventListener('input'"):block('function vpSave(){','function vpNum('),{currentId:'a',VPID:'a',VP:{client:'A'},MEM:false,document:{getElementById:()=>({textContent:'A'})},collect:()=>({value:'A'}),put:async(store,value)=>{writes.push(JSON.parse(JSON.stringify(value)));},alert(){}});const p=c[name]();c.currentId='b';c.VPID='b';c.VP={client:'B'};await p;assert.equal(writes[0].id,'a');});
test('quote zero quantity is blocked before any Xero write',()=>{let sent=0;const alerts=[],c=context(block('function xeroCreateQuote_()',"['qbClient'"),{QB:{xeroContact:{contactID:'c'},items:[{qty:0,sell:100}]},alert:m=>alerts.push(m),api:()=>{sent++;}});c.xeroCreateQuote_();assert.equal(sent,0);assert.match(alerts[0],/positive quantity/);});
test('calendar membership is exact rather than substring',()=>{const c=context(block('function calIsMine_','function calRender_'),{CAL_ALL:false,ME:{name:'Ann'}});assert.equal(c.calIsMine_({technician:'Joann'}),false);assert.equal(c.calIsMine_({technician:'Ann, Ben'}),true);});
test('all application and backend JavaScript parses',()=>{let n=0;for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);n++;}for(const file of ['supabase-client.js','xero-customer.js','timesheet-sync.js','sw.js','apps-script/Code.gs','apps-script/Stock.gs']){new vm.Script(fs.readFileSync(file,'utf8'),{filename:file});n++;}assert.ok(n>=7);JSON.parse(fs.readFileSync('manifest.webmanifest','utf8'));});
const backend=fs.readFileSync('apps-script/Code.gs','utf8');
function backendFunction(name){const start=backend.indexOf('function '+name+'('),end=backend.indexOf('\nfunction ',start+1);return backend.slice(start,end<0?undefined:end);}
for(const qty of [0,-1,'',null,'not a number',Infinity])test('backend rejects invalid quote quantity '+qty,()=>{const c=context(backendFunction('validateQuoteAmounts_'));assert.throws(()=>c.validateQuoteAmounts_(qty,100),/positive numbers/);});
test('backend preserves explicit zero price and negative adjustment price',()=>{const c=context(backendFunction('validateQuoteAmounts_'));c.validateQuoteAmounts_(1,0);c.validateQuoteAmounts_(1,-20);});
test('backend quote validation happens before Xero requests',()=>{let calls=0;const c=context(backendFunction('xeroCreateQuote_')+backendFunction('validateQuoteAmounts_'),{auth_:()=>({}),xeroCfg_:()=>{calls++;throw new Error('should not be called');}});assert.throws(()=>c.xeroCreateQuote_({quote:{contactID:'test',items:[{quantity:0,unitAmount:5}]}}),/positive numbers/);assert.equal(calls,0);});
test('worker assignment cannot match another name or empty name',()=>{const c=context(backendFunction('jobCardAssigned_'));assert.equal(c.jobCardAssigned_('Joann','Ann'),false);assert.equal(c.jobCardAssigned_('Ann, Bob','Ann'),true);assert.equal(c.jobCardAssigned_('Anyone',''),false);assert.equal(c.jobCardAssigned_(' ANN ; Bob ',' ann '),true);});
test('worker cannot take ownership of another existing Job Card by changing technician',()=>{let writes=0;const row=['id','JC','Client','Site','2026-09-24','Other'];const c=context(backendFunction('jobCardSaveLocked_')+backendFunction('jobCardAssigned_'),{auth_:()=>({name:'Ann',role:'Worker'}),jobCardsSheet_:()=>({getLastRow:()=>2,getRange:()=>({getValues:()=>[row],setValues:()=>{writes++;}}),appendRow:()=>{writes++;}})});assert.throws(()=>c.jobCardSaveLocked_({jobCard:{id:'id',customer:'Client',site:'Site',date:'2026-09-24',technicians:'Ann'}}),/another worker/);assert.equal(writes,0);});
test('Job Card write lock releases even when validation fails',()=>{let released=false;const c=context(backendFunction('jobCardSave_'),{LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){released=true;}})},jobCardSaveLocked_:()=>{throw new Error('validation');}});assert.throws(()=>c.jobCardSave_({}),/validation/);assert.ok(released);});
function transactionDB(initial){let stored=initial&&structuredClone(initial);return {read:()=>stored,transaction(){const t={objectStore:()=>({get(){const q={};queueMicrotask(()=>{q.result=stored&&structuredClone(stored);q.onsuccess();queueMicrotask(()=>t.oncomplete());});return q;},put(row){stored=structuredClone(row);}})};return t;}};}
for(const kind of ['newer revision','hidden record','same revision'])test('Job Card acknowledgement transaction: '+kind,async()=>{const db=transactionDB({id:'a',revision:kind==='newer revision'?'new':'sent',status:'DRAFT',deleted:kind==='hidden record',sections:{photo:{img:'photo'}}});const c=context(block('function jcAcknowledge_','function jcRefreshFromSupabase_'),{DB:db});const matched=await c.jcAcknowledge_({id:'a',revision:'sent'});assert.equal(matched,kind==='same revision');assert.equal(db.read().status,matched?'SUBMITTED':'DRAFT');assert.equal(db.read().sections.photo.img,'photo');});
test('remote refresh never overwrites an existing local photo or tombstone',async()=>{for(const deleted of [false,true]){const db=transactionDB({id:'a',deleted,sections:{photo:{img:'local-photo'}}});const c=context(block('function jcImportMissing_','function jcAcknowledge_'),{MEM:false,DB:db});await c.jcImportMissing_({id:'a',sections:{}});assert.equal(db.read().sections.photo.img,'local-photo');assert.equal(db.read().deleted,deleted);}});
test('unavailable persistent storage cannot report successful save',async()=>{const c=context(block('function put(store,val)','function getAll('),{MEM:true});await assert.rejects(c.put('props',{id:'p'}),/Persistent browser storage/);});
function stockContext(){let handler;const nodes=new Map(),d=deferred(),writes=[];const c=context(block("document.getElementById('stSend').addEventListener",'/* ============ admin ============ */'),{ST:{place:'Store',counts:{A:2,B:3},items:[{item:'A',Store:0},{item:'B',Store:0}],places:[],cats:[]},ME:{username:'a'},confirm:()=>true,alert(){},document:{getElementById(id){if(!nodes.has(id))nodes.set(id,{addEventListener(e,f){handler=f;}});return nodes.get(id);}},api:()=>d.promise,put:async(s,row)=>{writes.push(row);},saveStockDraft(){},renderPlaces(){},renderStock(){}});return {c,d,run:()=>handler(),writes};}
test('stock mixed response retains unknown items and newer edits',async()=>{const {c,d,run}=stockContext();run();c.ST.counts.A=8;d.resolve({changed:1,unknown:['B']});await tick();assert.equal(c.ST.counts.A,8);assert.equal(c.ST.counts.B,3);assert.equal(c.ST.items[0].Store,2);});
test('stock accepted snapshot removes only its matching count',async()=>{const {c,d,run}=stockContext();run();d.resolve({changed:1,unknown:['B']});await tick();assert.equal(c.ST.counts.A,undefined);assert.equal(c.ST.counts.B,3);});
test('stock reply after place change cannot clear the new place counts',async()=>{const {c,d,run}=stockContext();run();c.ST.place='GWM';c.ST.counts={A:2};d.resolve({changed:2,unknown:[]});await tick();assert.equal(c.ST.counts.A,2);assert.equal(c.ST.items[0].Store,2);});
test('malformed stock reply retains all input',async()=>{const {c,d,run}=stockContext();run();d.resolve({ok:true});await tick();assert.equal(c.ST.counts.A,2);assert.equal(c.ST.counts.B,3);});
test('service worker excludes credentials/API traffic and preserves other applications caches',()=>{const listeners={},c=context(fs.readFileSync('sw.js','utf8'),{URL,self:{location:{origin:'https://test.example'},registration:{scope:'https://test.example/app/'},addEventListener:(n,f)=>listeners[n]=f}});for(const url of ['https://script.google.com/exec?pass=private','https://test.example/app/exec?user=a','https://test.example/other/page']){let intercepted=false;listeners.fetch({request:{method:'GET',url,mode:'navigate'},respondWith(){intercepted=true;}});assert.equal(intercepted,false,url);}assert.ok(fs.readFileSync('sw.js','utf8').includes('/^flagship[-_]/i'));});
