// Execute the actual Apps Script handlers against disposable in-memory Sheets.
// This is contract coverage, NOT evidence of a deployed Google integration.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
function backend(){
 const sheets=new Map(),properties=new Map();
 function sheet(name){const sh={rows:[],tags:[],getName:()=>name,getLastRow(){return this.rows.length;},getLastColumn(){return Math.max(0,...this.rows.map(r=>r.length));},getMaxRows:()=>100,setFrozenRows(){},setColumnWidth(){},hideColumns(){},clear(){this.rows=[];},appendRow(r){this.getRange(this.rows.length+1,1,1,r.length).setValues([r]);},deleteRow(n){this.rows.splice(n-1,1);},getDeveloperMetadata(){return this.tags;},addDeveloperMetadata(k,v){this.tags.push({getKey:()=>k,getValue:()=>v});},getRange(r,c,n=1,m=1){const range={getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>sh.rows[r+i-1]?.[c+j-1]??'')),getValue(){return this.getValues()[0][0];},getFormulas:()=>Array.from({length:n},()=>Array(m).fill('')),setValues(values){values.forEach((row,i)=>{sh.rows[r+i-1]??=[];row.forEach((v,j)=>{sh.rows[r+i-1][c+j-1]=typeof v==='string'&&v.startsWith("'")?v.slice(1):v;});});return this;},setValue(v){return this.setValues([[v]]);},setFormulas(v){return this.setValues(v);},clearContent(){return this.setValues(Array.from({length:n},()=>Array(m).fill('')));}};for(const method of ['setNumberFormat','setFontWeight','setBackground','setFontColor','sort'])range[method]=()=>range;return range;}};sheets.set(name,sh);return sh;}
 const ss={getSheets:()=>[...sheets.values()],getSheetByName:n=>sheets.get(n),insertSheet:sheet};
 const c={Date,console:{error(){}},SpreadsheetApp:{getActiveSpreadsheet:()=>ss},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},Utilities:{DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(a,b)=>[...crypto.createHash('sha256').update(b).digest()],getUuid:()=>crypto.randomUUID()},PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties.get(k)||null,setProperty:(k,v)=>properties.set(k,v)})},ScriptApp:{getService:()=>({getUrl:()=> 'https://staging.invalid/exec'})},ContentService:{MimeType:{JSON:'json'},createTextOutput:text=>({text,setMimeType(){return this;}})},HtmlService:{XFrameOptionsMode:{ALLOWALL:'all'},createHtmlOutput:html=>({html,setXFrameOptionsMode(){return this;}})}};
 vm.createContext(c);vm.runInContext(fs.readFileSync('apps-script/Code.gs','utf8')+'\n'+fs.readFileSync('apps-script/Stock.gs','utf8'),c);
 for(const [name,head] of Object.entries(c.SHEETS))sheet(name).appendRow(Array.from(head));sheet('Stock').appendRow(Array.from(c.STOCK_HEAD));
 for(const [user,name,role] of [['admin','Test Admin','Admin'],['worker','Test Worker','Worker']])sheets.get('Users').appendRow([user,name,role,'Active',c.hash_(user,'fixture-only'),new Date(),'']);
 const post=(body,user='admin')=>JSON.parse(c.doPost({postData:{contents:JSON.stringify({user,pass:'fixture-only',...body})}}).text);
 const get=(body,user='admin')=>JSON.parse(c.doGet({parameter:{user,pass:'fixture-only',...body}}).text);
 return {c,sheets,post,get};
}
test('actual me/login reject wrong credentials and accept an active user',()=>{const b=backend();assert.equal(b.get({action:'me'}).user.role,'Admin');assert.equal(b.post({action:'login',pass:'wrong'}).ok,false);assert.equal(b.post({action:'login'}).user.username,'admin');});
test('actual Timesheet handlers accept, reject, read and retry without duplicates',()=>{const b=backend(),row={worker:'Test Worker',date:'2026-09-24',timeIn:'07:00',timeOut:'17:00',lunch:30,job:'fixture'};const first=b.post({action:'timesheets',rows:[row,{...row,date:'2026-09-23',lunch:''}]});assert.equal(first.ok,true);assert.deepEqual(first.results.map(r=>r.status),['added','skipped']);const retry=b.post({action:'timesheets',rows:[row]});assert.equal(retry.results[0].status,'unchanged');assert.equal(b.sheets.get('Timesheets').rows.length,2);assert.equal(b.get({action:'timesheetAll',cycle:'2026-09'}).entries['Test Worker']['2026-09-24'].lu,30);});
test('actual Timesheet endpoint refuses worker impersonation',()=>{const b=backend(),r=b.post({action:'timesheets',rows:[{worker:'Someone Else',date:'2026-09-24',timeIn:'07:00',timeOut:'17:00',lunch:0}]},'worker');assert.equal(r.results[0].status,'blocked');assert.equal(b.sheets.get('Timesheets').rows.length,1);});
test('actual Job Card endpoints save, edit, list, reject unauthorized delete and delete',()=>{const b=backend(),card={id:'fixture-card',customer:'Synthetic',site:'Test',date:'2026-09-24',technicians:'Test Worker',status:'SUBMITTED',types:['custom'],sections:{}};assert.equal(b.post({action:'jobCardSave',jobCard:card}).id,card.id);card.site='Edited';assert.equal(b.post({action:'jobCardSave',jobCard:card}).ok,true);assert.equal(b.get({action:'jobCards'},'worker').jobCards[0].data.site,'Edited');assert.equal(b.sheets.get('JobCards').rows.length,2);assert.equal(b.post({action:'jobCardDelete',id:card.id},'worker').ok,false);assert.equal(b.post({action:'jobCardDelete',id:card.id}).ok,true);assert.equal(b.get({action:'jobCards'}).jobCards.length,0);});
test('actual stock endpoint changes only selected location and returns unknown rows',()=>{const b=backend();b.sheets.get('Stock').appendRow(['Fixture cable','Other','each',10,5,7,9,'','','']);const r=b.post({action:'stockCount',place:'Store',counts:{'Fixture cable':0,'Not listed':3}});assert.equal(r.ok,true);assert.equal(r.changed,1);assert.deepEqual(r.unknown,['Not listed']);assert.deepEqual(b.sheets.get('Stock').rows[1].slice(4,7),[0,7,9]);});
test('actual proposal publish, view and accept persist the expected state',()=>{const b=backend(),r=b.post({action:'proposalPublish',proposal:{client:'Synthetic',items:[{desc:'Fixture',qty:2,sell:100}]}});assert.equal(r.ok,true);assert.match(b.c.proposalPublicHtml_(r.token).html,/230/);assert.equal(b.c.proposalAccept_(r.token,'Test').status,'ACCEPTED');assert.equal(b.c.proposalAccept_(r.token,'Test').status,'ACCEPTED');assert.equal(b.sheets.get('Proposals').rows.length,2);});
test('missing Xero credentials fail closed without external financial writes',()=>{const b=backend();let sent=0;b.c.UrlFetchApp={fetch(){sent++;throw Error('not allowed');}};const r=b.post({action:'xeroCreateQuote',quote:{contactID:'fixture',items:[{quantity:1,unitAmount:100}]}});assert.equal(r.ok,false);assert.match(r.error,/not configured/);assert.equal(sent,0);});
test('missing Supabase server config is an explicit price integration blocker',()=>{const b=backend(),r=b.get({action:'prices'});assert.equal(r.ok,false);assert.match(r.error,/Supabase server settings are missing/);});
test('public proposal escapes quotes in customer-controlled HTML attributes',()=>{const b=backend();assert.equal(b.c.escXeroHtml_('" onfocus="test'),'&quot; onfocus=&quot;test');});
