// Execute the actual Apps Script handlers against disposable in-memory Sheets.
// This is contract coverage, NOT evidence of a deployed Google integration.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
function backend(){
 const sheets=new Map(),properties=new Map();
 function sheet(name){const sh={rows:[],tags:[],getName:()=>name,getLastRow(){return this.rows.length;},getLastColumn(){return Math.max(0,...this.rows.map(r=>r.length));},getMaxRows:()=>100,setFrozenRows(){},setColumnWidth(){},hideColumns(){},clear(){this.rows=[];},appendRow(r){this.getRange(this.rows.length+1,1,1,r.length).setValues([r]);},deleteRow(n){this.rows.splice(n-1,1);},getDeveloperMetadata(){return this.tags;},addDeveloperMetadata(k,v){this.tags.push({getKey:()=>k,getValue:()=>v});},getRange(r,c,n=1,m=1){const range={getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>sh.rows[r+i-1]?.[c+j-1]??'')),getValue(){return this.getValues()[0][0];},getFormulas:()=>Array.from({length:n},()=>Array(m).fill('')),setValues(values){values.forEach((row,i)=>{sh.rows[r+i-1]??=[];row.forEach((v,j)=>{sh.rows[r+i-1][c+j-1]=typeof v==='string'&&v.startsWith("'")?v.slice(1):v;});});return this;},setValue(v){return this.setValues([[v]]);},setFormulas(v){return this.setValues(v);},clearContent(){return this.setValues(Array.from({length:n},()=>Array(m).fill('')));}};for(const method of ['setNumberFormat','setFontWeight','setBackground','setFontColor','sort'])range[method]=()=>range;return range;}};sheets.set(name,sh);return sh;}
 const ss={getSheets:()=>[...sheets.values()],getSheetByName:n=>sheets.get(n),insertSheet:sheet};
 const c={Date,console:{error(){}},SpreadsheetApp:{getActiveSpreadsheet:()=>ss},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},Utilities:{DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(a,b)=>[...crypto.createHash('sha256').update(b).digest()],getUuid:()=>crypto.randomUUID()},PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties.get(k)||null,setProperty:(k,v)=>properties.set(k,v)})},ScriptApp:{getService:()=>({getUrl:()=> 'https://staging.invalid/exec'})},ContentService:{MimeType:{JSON:'json'},createTextOutput:text=>({text,setMimeType(){return this;}})},HtmlService:{XFrameOptionsMode:{ALLOWALL:'all'},createHtmlOutput:html=>({html,setXFrameOptionsMode(){return this;}})}};
 vm.createContext(c);vm.runInContext(fs.readFileSync('apps-script/Code.gs','utf8')+'\n'+fs.readFileSync('apps-script/Stock.gs','utf8'),c);
 for(const [name,head] of Object.entries(c.SHEETS))sheet(name).appendRow(Array.from(head));sheet('Stock').appendRow(Array.from(c.STOCK_HEAD));
 for(const [user,name,role] of [['admin','Test Admin','Admin'],['worker','Test Worker','Worker']])sheets.get('Users').appendRow([user,name,role,'Active',c.hash_(user,'fixture-only'),new Date(),'']);
 const post=(body,user='admin')=>JSON.parse(c.doPost({postData:{contents:JSON.stringify({user,pass:'fixture-only',...body})}}).text);
 const get=(body,user='admin')=>JSON.parse(c.doGet({parameter:{user,pass:'fixture-only',...body}}).text);
 return {c,sheets,post,get};
}
test('actual me/login reject wrong credentials and accept an active user',()=>{const b=backend();assert.equal(b.get({action:'me'}).user.role,'Admin');assert.equal(b.post({action:'login',pass:'wrong'}).ok,false);assert.equal(b.post({action:'login'}).user.username,'admin');});
test('actual Timesheet handlers accept, reject, read and retry without duplicates',()=>{const b=backend(),row={worker:'Test Worker',date:'2026-09-24',timeIn:'07:00',timeOut:'17:00',lunch:30,job:'fixture'};const first=b.post({action:'timesheets',rows:[row,{...row,date:'2026-09-23',lunch:''}]});assert.equal(first.ok,true);assert.deepEqual(first.results.map(r=>r.status),['added','skipped']);const retry=b.post({action:'timesheets',rows:[row]});assert.equal(retry.results[0].status,'unchanged');assert.equal(b.sheets.get('Timesheets').rows.length,2);assert.equal(b.get({action:'timesheetAll',cycle:'2026-09'}).entries['Test Worker']['2026-09-24'].lu,30);});
test('actual Timesheet endpoint refuses worker impersonation',()=>{const b=backend(),r=b.post({action:'timesheets',rows:[{worker:'Someone Else',date:'2026-09-24',timeIn:'07:00',timeOut:'17:00',lunch:0}]},'worker');assert.equal(r.results[0].status,'blocked');assert.match(r.results[0].reason,/own timesheet/);assert.equal(b.sheets.get('Timesheets').rows.length,1);});
test('actual Job Card endpoints save, edit, list, reject unauthorized delete and delete',()=>{const b=backend(),card={id:'fixture-card',customer:'Synthetic',site:'Test',date:'2026-09-24',technicians:'Test Worker',status:'SUBMITTED',types:['custom'],sections:{}};assert.equal(b.post({action:'jobCardSave',jobCard:card}).id,card.id);card.site='Edited';assert.equal(b.post({action:'jobCardSave',jobCard:card}).ok,true);assert.equal(b.get({action:'jobCards'},'worker').jobCards[0].data.site,'Edited');assert.equal(b.sheets.get('JobCards').rows.length,2);assert.equal(b.post({action:'jobCardDelete',id:card.id},'worker').ok,false);assert.equal(b.post({action:'jobCardDelete',id:card.id}).ok,true);assert.equal(b.get({action:'jobCards'}).jobCards.length,0);});
test('actual Job Card endpoint rejects malformed central records before writing',()=>{const b=backend(),base={id:'bad-card',customer:'Synthetic',site:'Test',date:'2026-09-24',technicians:'Test Worker',status:'SUBMITTED',types:['custom'],sections:{}};for(const card of [{...base,types:[]},{...base,sections:null},{...base,status:'BROKEN'}]){const r=b.post({action:'jobCardSave',jobCard:card});assert.equal(r.ok,false);}assert.equal(b.sheets.get('JobCards').rows.length,1);});
test('actual stock endpoint changes only selected location and returns unknown rows',()=>{const b=backend();b.sheets.get('Stock').appendRow(['Fixture cable','Other','each',10,5,7,9,'','','']);const r=b.post({action:'stockCount',place:'Store',counts:{'Fixture cable':0,'Not listed':3}});assert.equal(r.ok,true);assert.equal(r.changed,1);assert.deepEqual(r.unknown,['Not listed']);assert.deepEqual(r.rejected,[]);assert.deepEqual(b.sheets.get('Stock').rows[1].slice(4,7),[0,7,9]);});
test('actual stock endpoint rejects invalid and fractional physical counts',()=>{const b=backend();b.sheets.get('Stock').appendRow(['Fixture cable','Other','each',10,5,7,9,'','','']);const r=b.post({action:'stockCount',place:'Store',counts:{'Fixture cable':1.5}});assert.deepEqual(r.rejected,['Fixture cable']);assert.equal(b.sheets.get('Stock').rows[1][4],5);});
test('actual proposal publish, view and accept persist the expected state',()=>{const b=backend(),r=b.post({action:'proposalPublish',proposal:{client:'Synthetic',items:[{desc:'Fixture',qty:2,sell:100}]}});assert.equal(r.ok,true);assert.match(b.c.proposalPublicHtml_(r.token).html,/230/);assert.equal(b.c.proposalAccept_(r.token,'Test').status,'ACCEPTED');assert.equal(b.c.proposalAccept_(r.token,'Test').status,'ACCEPTED');assert.equal(b.sheets.get('Proposals').rows.length,2);});
test('missing Xero credentials fail closed without external financial writes',()=>{const b=backend();let sent=0;b.c.UrlFetchApp={fetch(){sent++;throw Error('not allowed');}};const r=b.post({action:'xeroCreateQuote',quote:{contactID:'fixture',items:[{quantity:1,unitAmount:100}]}});assert.equal(r.ok,false);assert.match(r.error,/not configured/);assert.equal(sent,0);});
test('price reads return the same Sheet values that supplier imports update without requiring Supabase',()=>{const b=backend();b.sheets.get('Prices').appendRow(['fixture','Other','Test','SKU','Synthetic','each',100,'Cost',20,0,'','Yes','']);assert.equal(b.get({action:'prices'}).prices[0].cost,100);b.post({action:'updatePriceList',updates:[{code:'SKU',price:110}]});assert.equal(b.get({action:'prices'}).prices[0].cost,110);assert.equal(b.get({action:'prices'}).prices[0].sell,132);});
test('public proposal escapes quotes in customer-controlled HTML attributes',()=>{const b=backend();assert.equal(b.c.escXeroHtml_('" onfocus="test'),'&quot; onfocus=&quot;test');});
test('supplier update rejects missing or non-price values without overwriting existing costs',()=>{
 const b=backend(),sh=b.sheets.get('Prices');
 sh.appendRow(['fixture','Other','Test','SKU','Synthetic','each',100,'Cost',0,0,0,'','']);
 for(const price of ['', ' ', null, undefined, false, [], -1]){
  const r=b.post({action:'updatePriceList',updates:[{code:'SKU',price}]});
  assert.equal(r.ok,true);assert.equal(r.updated,0);assert.equal(sh.rows[1][6],100);
 }
 const r=b.post({action:'updatePriceList',updates:[{code:'SKU',price:0}]});
 assert.equal(r.ok,true);assert.equal(r.updated,1);assert.equal(sh.rows[1][6],0);
});

test('proposal Xero handoff is serialized to protect against duplicate quote creation',()=>{const src=fs.readFileSync('apps-script/Code.gs','utf8');assert.match(src,/function proposalSendToXero_\(body\)\{[\s\S]{0,220}getScriptLock\(\)/);assert.match(src,/proposalSendToXeroLocked_\(body\)/);});

test('actual Calendar endpoints persist central schedules and restrict worker writes',()=>{const b=backend(),e={id:'cal-fixture',customer:'Synthetic',site:'Test',date:'2026-09-28',startTime:'08:00',endTime:'10:00',technician:'Test Worker',jobType:'Electrical Work',status:'SCHEDULED'};assert.equal(b.post({action:'calendarSave',event:e}).id,e.id);assert.equal(b.get({action:'calendar'}).events.length,1);assert.equal(b.get({action:'calendar'},'worker').events[0].customer,'Synthetic');assert.equal(b.post({action:'calendarSave',event:{...e,id:'worker-edit'}},'worker').ok,false);});

test('user administration protects the active admin account and validates state',()=>{const b=backend();assert.equal(b.post({action:'setUser',target:'admin',status:'Suspended'}).ok,false);assert.equal(b.post({action:'setUser',target:'admin',status:'BROKEN'}).ok,false);});
test('password changes require at least eight characters',()=>{const b=backend();assert.equal(b.post({action:'changePassword',newPass:'1234567'}).ok,false);assert.equal(b.post({action:'resetPassword',target:'worker',newPass:'1234567'}).ok,false);});

test('privilege editor lists real usernames with separate company catalogs',()=>{const b=backend(),f=b.get({action:'userPermissions',company:'Flagship Solar'}),h=b.get({action:'userPermissions',company:'Hi Service'});assert.equal(f.ok,true);assert.ok(f.users.some(u=>u.username==='worker'));assert.ok(f.catalog.some(p=>p.key==='prices.manage'));assert.ok(!h.catalog.some(p=>p.key==='prices.manage'));assert.ok(h.catalog.some(p=>p.key==='stock.transfer'));});
test('worker cannot change privileges through a direct API request',()=>{const b=backend(),r=b.post({action:'saveUserPermissions',target:'worker',company:'Hi Service',permissions:['stock.adjust']},'worker');assert.equal(r.ok,false);assert.equal(b.sheets.has('UserPermissions'),false);});
test('revoked count permission blocks writes and cannot be bypassed by changing company',()=>{const b=backend();b.sheets.get('Stock').appendRow(['Fixture cable','Other','each',10,5,7,9,'','','']);assert.equal(b.post({action:'saveUserPermissions',target:'worker',company:'Flagship Solar',permissions:['stock.view']}).ok,true);const r=b.post({action:'stockCount',company:'Hi Service',place:'Store',counts:{'Fixture cable':0}},'worker');assert.equal(r.ok,false);assert.match(r.error,/Permission denied/);assert.equal(b.sheets.get('Stock').rows[1][4],5);assert.ok(b.get({action:'userAccess',company:'Hi Service'},'worker').permissions.includes('stock.count'));});
test('explicit price grant works while unknown keys and self lockout are rejected',()=>{const b=backend();assert.equal(b.post({action:'saveUserPermissions',target:'worker',permissions:['prices.view','prices.manage']}).ok,true);b.sheets.get('Prices').appendRow(['id','Other','Supplier','A','Fixture','each',10,'Cost',20,0,'','Yes','']);assert.equal(b.post({action:'savePrice',item:{id:'id',description:'Fixture',category:'Other',cost:11}},'worker').ok,true);assert.equal(b.post({action:'saveUserPermissions',target:'worker',permissions:['not.a.permission']}).ok,false);assert.equal(b.post({action:'saveUserPermissions',target:'admin',permissions:[]}).ok,false);});
test('saved grants persist and a subsequent empty selection revokes them',()=>{const b=backend();b.post({action:'saveUserPermissions',target:'worker',company:'Hi Service',permissions:['stock.view','stock.count']});assert.deepEqual(b.get({action:'userAccess',company:'Hi Service'},'worker').permissions,['stock.view','stock.count']);b.post({action:'saveUserPermissions',target:'worker',company:'Hi Service',permissions:[]});assert.deepEqual(b.get({action:'userAccess',company:'Hi Service'},'worker').permissions,[]);assert.throws(()=>b.c.auth_({action:'hiStockCount',company:'Flagship Solar',user:'worker',pass:'fixture-only'}),/Permission denied/);});
test('deleting a username clears its grants in both apps',()=>{const b=backend();for(const company of ['Flagship Solar','Hi Service'])b.post({action:'saveUserPermissions',target:'worker',company,permissions:[]});assert.equal(b.post({action:'deleteUser',target:'worker'}).ok,true);assert.equal(b.sheets.get('UserPermissions').rows.length,1);});

test('ambiguous stock descriptions remain rejected instead of overwriting the last duplicate',()=>{const b=backend();for(const n of [5,9])b.sheets.get('Stock').appendRow(['Duplicate','Other','each',10,n,0,0,'','','']);let r=b.post({action:'stockCount',place:'Store',counts:{Duplicate:2}});assert.deepEqual(r.rejected,['Duplicate']);assert.equal(r.changed,0);assert.deepEqual(b.sheets.get('Stock').rows.slice(1).map(r=>r[4]),[5,9]);assert.equal(b.post({action:'stockUpload',place:'Store',rows:[{item:'Duplicate',qty:1}]}).ok,false)});
test('blank null and boolean supplier fallback costs cannot become zero',()=>{for(const cost of ['',null,false]){const b=backend();b.sheets.get('Prices').appendRow(['id','Other','Supplier','A','Fixture','each',10,'Cost',20,0,'','Yes','']);assert.equal(b.post({action:'savePrice',existingOnly:true,costOnly:true,item:{id:'id',description:'Fixture',cost}}).ok,false);assert.equal(b.sheets.get('Prices').rows[1][6],10)}});
test('received stock creates daily audit movement with old and new quantity',()=>{const b=backend();b.sheets.get('Stock').appendRow(['Fixture','Other','each',10,5,0,0,'','','']);let r=b.post({action:'stockUpload',place:'Store',rows:[{item:'Fixture',qty:3}]});assert.equal(r.ok,true);assert.deepEqual(b.sheets.get('Stock_Counts').rows[1].slice(3),['Fixture',5,8,3])});
test('direct supplier bulk API cannot update duplicate codes or sell-price rows',()=>{const b=backend(),sh=b.sheets.get('Prices');for(const [id,code,type,cost] of [['a','DUP','Cost',10],['b','DUP','Cost',20],['s','SELL','Sell',40],['c','OK','Cost',5]])sh.appendRow([id,'Other','Test',code,'Fixture','each',cost,type,20,2,'spec','Yes','']);let r=b.post({action:'updatePriceList',updates:[{code:'DUP',price:99},{code:'SELL',price:99},{code:'OK',price:6}]});assert.equal(r.updated,1);assert.equal(r.conflicts.length,2);assert.deepEqual(sh.rows.slice(1).map(r=>r[6]),[10,20,40,6]);assert.equal(sh.rows[4][8],20);assert.equal(sh.rows[4][10],'spec')});
test('duplicate price IDs cannot edit or delete an arbitrary existing row',()=>{const b=backend(),sh=b.sheets.get('Prices');for(const code of ['A','B'])sh.appendRow(['same','Other','Test',code,'Fixture','each',10,'Cost',20,0,'','Yes','']);assert.equal(b.post({action:'savePrice',item:{id:'same',description:'Fixture',cost:11}}).ok,false);assert.equal(b.post({action:'deletePrice',id:'same'}).ok,false);assert.equal(sh.rows.length,3);assert.equal(sh.rows[1][6],10)});

test('new price IDs remain unique even when created in the same millisecond with fixed random',()=>{const b=backend();b.c.Date=class extends Date{static now(){return 123456789}};b.c.Math=Object.create(Math);b.c.Math.random=()=>0.5;const ids=Array.from({length:1000},()=>b.c.priceId_());assert.equal(new Set(ids).size,1000)});

test('actual supplier creation adds new records once, preserves existing data and rejects invalid rows',()=>{const b=backend();b.sheets.get('Prices').appendRow(['keep','Heat pump','ITS','OLD','Existing','each',500,'Cost',15,15000,'Keep specs','Yes',new Date()]);const before=JSON.stringify(b.sheets.get('Prices').rows[1]);const items=[{code:'OLD',description:'Overwrite attempt',cost:1},{code:'NEW',description:'New supplier item',cost:120,supplier:'Apple',category:'Consumable'},{code:'NEW',description:'Duplicate',cost:130},{code:'BAD',description:'Invalid',cost:-1}];const r=b.post({action:'createSupplierPrices',source:'fixture.pdf',items});assert.equal(r.ok,true);assert.equal(r.created,1);assert.equal(r.existing,2);assert.equal(r.failed,1);assert.equal(JSON.stringify(b.sheets.get('Prices').rows[1]),before);const created=b.sheets.get('Prices').rows[2];assert.equal(created[2],'Apple');assert.equal(created[6],120);assert.equal(created[7],'Cost');assert.equal(created[8],'');assert.equal(created[9],0);const retry=b.post({action:'createSupplierPrices',items:items.slice(0,3)});assert.equal(retry.created,0);assert.equal(b.sheets.get('Prices').rows.length,3);});

test('original ITS and Apple layouts can populate missing products and repeat without duplicates',async()=>{const b=backend(),html=fs.readFileSync('index.html','utf8'),c={money:String,normCode_:s=>String(s||'').trim().toUpperCase()};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('function csvRows_'),html.indexOf('async function readSupplierFile_')),c);function pdf(name){const pages=JSON.parse(fs.readFileSync('tests/fixtures/'+name));return {numPages:pages.length,getPage:async n=>({getTextContent:async()=>({items:pages[n-1]})})};}const its=await c.puParseITS_(pdf('its-dealer-layout.json'),()=>{}),apple=await c.puParseApple_(pdf('apple-product-layout.json'),()=>{});const codes=['ITS-3.6HD','ITS-4.5HDsuper','ITS-5.4HD','ITS-7.6HD','ITS-22HD3','ITS-6.3HDsuper','ITS-11HD','ITS-50VD3pro'];const items=rows=>Array.from(rows,r=>({code:r.code,description:r.description,cost:r.price,supplier:r.supplier,category:'Other'}));assert.equal(b.post({action:'createSupplierPrices',items:items(its.filter(r=>codes.includes(r.code)))}).created,8);const first=b.post({action:'createSupplierPrices',items:items(its)});assert.equal(first.created,96);assert.equal(first.existing,8);assert.equal(first.failed,0);assert.equal(b.post({action:'createSupplierPrices',items:items(its)}).created,0);assert.equal(b.post({action:'createSupplierPrices',items:items(apple)}).created,6);assert.equal(b.post({action:'createSupplierPrices',items:items(apple)}).created,0);assert.equal(b.sheets.get('Prices').rows.length,111);});
