const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
// The original outside-Timesheet byte hashes applied only to Checkpoint 1.
// Michael subsequently authorised cross-module repairs; retain its runtime gates
// and use application-integrity.test.cjs for the changed modules.
test('deployed calendar, bilingual proposal and PDF modules remain present',()=>{const h=fs.readFileSync('index.html','utf8');for(const name of ['calRender_','vpSave','jcBuildPdf_','xeroSyncItems_'])assert.ok(h.includes('function '+name+'('),name);});
test('Supabase adapter has one Job Card list handler and valid returning select',()=>{const s=fs.readFileSync('supabase-client.js','utf8');assert.equal((s.match(/listJobCards: function/g)||[]).length,1);assert.ok(s.includes('on_conflict=client_id&select=*'));});
test('customer helper uses the explicit quote bridge',()=>{const s=fs.readFileSync('xero-customer.js','utf8');assert.ok(s.includes('window.FlagshipQuoteBridge'));assert.ok(!s.includes('window.QB'));});
test('database still opens v5 and retains calendar store',async()=>{const h=fs.readFileSync('index.html','utf8'),stores=new Set(['jobs','clauses','cfg','props','quotes','jobcards','calendar']);const context={indexedDB:{open(name,version){assert.equal(name,'flagship-inspections');assert.equal(version,5);const req={result:{objectStoreNames:{contains:n=>stores.has(n)},createObjectStore:n=>{stores.add(n);}}};queueMicrotask(()=>req.onsuccess());return req;}}};vm.createContext(context);vm.runInContext(h.slice(h.indexOf('var DB=null'),h.indexOf('function tx(')),context);await context.open();assert.ok(context.DB);assert.equal(stores.size,7);});
test('release shell and HTML contain both helpers with existing assets',()=>{const sw=fs.readFileSync('sw.js','utf8'),h=fs.readFileSync('index.html','utf8');assert.ok(sw.includes('flagship-repairs-v86'));const shell=vm.runInNewContext(sw.match(/const SHELL = (\[[\s\S]*?\]);/)[1]);for(const p of shell)assert.ok(fs.existsSync(p),p);for(const p of ['timesheet-sync.js','xero-customer.js']){assert.ok(shell.includes('./'+p));assert.ok(h.includes('src="./'+p+'"'));}assert.ok(!shell.some(p=>/tests|REPAIR/.test(p)));});
