const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('index.html','utf8');
function context(prices=[]){const c={PRICES:prices,money:String};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('function csvRows_'),html.indexOf('async function readSupplierFile_')),c);vm.runInContext(html.slice(html.indexOf('function normCode_'),html.indexOf('function renderPriceUpdater_')),c);return c;}
function pdf(name){const pages=JSON.parse(fs.readFileSync('tests/fixtures/'+name));return {numPages:pages.length,getPage:async n=>({getTextContent:async()=>({items:pages[n-1]})})};}
test('Apple invoice recognises spaced inclusive price header and all six products',async()=>{const rows=await context().puParseApple_(pdf('apple-product-layout.json'),()=>{});assert.equal(rows.length,6);assert.equal(new Set(rows.map(r=>r.code)).size,6);assert.ok(rows.every(r=>r.price>0));});
test('ITS dealer baseline offsets retain all 104 products and correct heatpump costs',async()=>{const rows=await context().puParseITS_(pdf('its-dealer-layout.json'),()=>{});assert.equal(rows.length,104);for(const [code,price] of [['ITS-3.6HD',10390],['ITS-7.6HD',13540],['ITS-22HD3',27925]])assert.equal(rows.find(r=>r.code===code).price,price);});
test('ITS compatibility descriptions never select a heatpump as the accessory target',()=>{const c=context([{id:'pump',code:'ITS-22HD3',description:'ITS heatpump',spec:'CP130 circulation pump',cost:27925,type:'Cost'}]);const p=c.buildPricePreview_([{code:'CP130',description:'Circulation pump compatible with ITS-22HD3',price:3790}]);assert.equal(p.changes.length,0);});
test('duplicate supplier codes require an explicit existing ID selection',()=>{const c=context([{id:'a',code:'DUP',cost:10,type:'Cost'},{id:'b',code:'DUP',cost:20,type:'Cost'}]);const rows=[{code:'DUP',price:30}];assert.equal(c.buildPricePreview_(rows).conflicts.length,1);const p=c.buildPricePreview_(rows,{DUP:'b'});assert.equal(p.changes.length,1);assert.equal(p.changes[0].current.id,'b');assert.equal(c.buildPricePreview_(rows,{DUP:'missing'}).conflicts.length,1);});
test('two supplier rows cannot overwrite the same existing target',()=>{const c=context([{id:'a',code:'',description:'Unique product description',cost:10,type:'Cost'}]);const p=c.buildPricePreview_([{code:'FIRST',description:'Unique product description',price:20},{code:'SECOND',description:'Unique product description',price:30}]);assert.equal(p.changes.length,0);assert.equal(p.conflicts.length,2);});
