const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {normalize}=require('../connector/normalize.cjs'),{TimeTreeClient}=require('../connector/timetree-client.cjs'),{publish}=require('../connector/sync.cjs');
function backend(){
  const source=fs.readFileSync('tests/backend-release.test.cjs','utf8').split("test('actual me/login")[0];
  const host={require,console};vm.createContext(host);vm.runInContext(source,host);const b=host.backend();
  for(const sh of b.sheets.values()){sh.getMaxColumns=()=>26;sh.insertColumnsAfter=()=>{};}
  const ss=b.c.SpreadsheetApp.getActiveSpreadsheet(),insert=ss.insertSheet;
  ss.insertSheet=name=>{const sh=insert(name);sh.getMaxColumns=()=>26;sh.insertColumnsAfter=()=>{};return sh;};
  vm.runInContext(fs.readFileSync('apps-script/TimeTree.gs','utf8'),b.c);
  b.c.PropertiesService.getScriptProperties().setProperty('TIMETREE_CONNECTOR_TOKEN_SHA256',b.c.ttDigest_('fixture-token'));
  b.import=events=>b.post({action:'timeTreeImport',connectorToken:'fixture-token',requestId:'fixture',events});return b;
}
function event(overrides={}){return normalize({uuid:'event-1',calendar_id:63108444,title:'Synthetic booking',start_at:1791370800000,end_at:1791374400000,start_timezone:'Africa/Johannesburg',end_timezone:'Africa/Johannesburg',updated_at:100,label_id:1,attendees:[1],note:'Do not lose\nStock required: cable',...overrides},{id:63108444,name:'Scheduling Calender',alias_code:'test',calendar_labels:[{id:1,name:'Flagship Electric'}],calendar_users:[{id:1,name:'Test Worker'}]});}
test('source times, notes, attendees and unmodelled fields survive normalization',()=>{const e=event({unknown:{nested:['original']}});assert.equal(e.startTime,'13:00');assert.equal(e.date,'2026-10-07');assert.equal(e.technician,'Test Worker');assert.deepEqual(e.raw.unknown,{nested:['original']});assert.match(e.notes,/Stock required/);});
test('opening imported booking shows source details without creating a job card',async()=>{const html=fs.readFileSync('index.html','utf8'),start=html.indexOf('var calOpening_='),code=html.slice(start,html.indexOf("document.getElementById('calNew')",start)),elements={};const c={Promise,TimeTreeCalendar:{details:e=>e.notes},get1:async()=>event(),document:{getElementById:id=>elements[id]||(elements[id]={classList:{remove(){}},textContent:'',href:''})},confirm:assert.fail,jcBlank:assert.fail,alert:assert.fail};vm.createContext(c);vm.runInContext(code,c);await c.calOpen_('event-1');assert.match(elements.calTTText.textContent,/Stock required/);assert.match(elements.calTTSource.href,/timetreeapp.com/);});
test('all-day UTC dates do not shift with local timezone',()=>{const e=event({all_day:true,start_at:Date.parse('2026-10-07T00:00:00Z'),end_at:Date.parse('2026-10-08T00:00:00Z')});assert.equal(e.date,'2026-10-07');assert.equal(e.endDate,'2026-10-08');assert.equal(e.startTime,'');});
test('actual import retries do not duplicate mirror or unchanged revision; changes preserve history',()=>{const b=backend(),e=event();assert.equal(b.import([e]).ok,true);assert.equal(b.import([e]).changed,0);const changed=event({title:'Changed booking',updated_at:101});assert.equal(b.import([changed]).changed,1);assert.equal(b.sheets.get('TimeTreeEvents').rows.length,2);assert.equal(b.sheets.get('TimeTreeHistory').rows.length,3);assert.equal(JSON.parse(b.sheets.get('TimeTreeHistory').rows[1][4]).notes,e.notes);assert.equal(b.get({action:'calendar'}).events[0].customer,'Changed booking');assert.equal(b.get({action:'hiCalendar'}).events.length,0);});
test('invalid token and malformed later record leave all source and app rows untouched',()=>{const b=backend(),e=event();assert.equal(b.post({action:'timeTreeImport',connectorToken:'bad',events:[e]}).ok,false);assert.equal(b.import([e,{...event({uuid:'two'}),date:'bad'}]).ok,false);assert.ok(!b.sheets.has('TimeTreeEvents'));assert.equal(b.sheets.get('Calendar').rows.length,1);assert.equal(b.sheets.get('Stock').rows.length,1);});
test('older source cannot overwrite newer booking; missing records do not delete mirror',()=>{const b=backend();b.import([event({updated_at:200,title:'Latest'})]);assert.equal(b.import([event({updated_at:100,title:'Old'})]).changed,0);b.import([event({uuid:'other'})]);assert.equal(b.get({action:'calendar'}).events.length,2);assert.equal(b.get({action:'calendar'}).events.find(e=>e.id.endsWith(':event-1')).customer,'Latest');});
test('calendar routing, explicit view grants and worker assignment are enforced on actual reads',()=>{const b=backend(),a=event();b.sheets.get('Users').rows.find(r=>r[0]==='worker')[1]='Andre';a.targets=['Hi Service'];a.jobType='Andre';b.import([a,event({uuid:'unassigned',attendees:[]})]);assert.equal(b.get({action:'calendar'},'worker').events.length,0);assert.equal(b.get({action:'hiCalendar'},'worker').events.length,1);assert.equal(b.post({action:'saveUserPermissions',company:'Hi Service',target:'worker',permissions:[]}).ok,true);assert.equal(b.get({action:'hiCalendar'},'worker').ok,false);});
test('explicit source archive preserves full record and TimeTree identities cannot be manually overwritten',()=>{const b=backend();b.import([event({deactivated_at:123})]);assert.equal(b.get({action:'calendar'}).events[0].status,'ARCHIVED');assert.equal(b.post({action:'calendarSave',event:event()}).ok,false);assert.ok(b.sheets.get('TimeTreeHistory').rows[1][4].includes('deactivated_at'));});
test('pagination loops and malformed responses fail without publishing a partial calendar',async()=>{const c=new TimeTreeClient({fetchImpl:async()=>({ok:true,json:async()=>({events:[],chunk:true,since:1})}),delayMs:0});await assert.rejects(c.events(1),/stopped advancing/);const bad=new TimeTreeClient({fetchImpl:async()=>({ok:true,json:async()=>({events:[]})})});await assert.rejects(bad.events(1),/Unexpected/);});
test('lost or incomplete publish acknowledgement prevents reporting successful import',async()=>{await assert.rejects(publish([event()],{APPS_SCRIPT_URL:'https://script.google.com/macros/s/test/exec',TIMETREE_CONNECTOR_TOKEN:'fixture'},async()=>({ok:true,json:async()=>({ok:true,acceptedIds:[]})})),/not fully acknowledged/);});
test('repeating bookings respect exceptions, keep time and multi-day bookings appear on each day',()=>{global.rrule=require('../vendor/rrule.min.js');const view=require('../timetree-calendar.js');const e=event({all_day:true,start_at:Date.parse('2026-10-03T00:00:00Z'),end_at:Date.parse('2026-10-03T00:00:00Z'),recurrences:['RRULE:FREQ=WEEKLY;INTERVAL=2','EXDATE:20261017T000000Z']});const j=view.entries([e],'2026-10-01','2026-10-31');assert.deepEqual(j.events.map(e=>e.displayDate),['2026-10-03','2026-10-31']);assert.deepEqual(j.errors,[]);const multi=event({all_day:true,start_at:Date.parse('2026-10-01T00:00:00Z'),end_at:Date.parse('2026-10-03T00:00:00Z')});assert.equal(view.entries([multi],'2026-10-01','2026-10-31').events.length,3);});
function nativeBackend(failSecond=false){const b=backend(),props=b.c.PropertiesService.getScriptProperties();props.setProperty('TIMETREE_EMAIL','fixture@example.invalid');props.setProperty('TIMETREE_PASSWORD','fixture-only');b.c.LockService.getScriptLock=()=>({tryLock:()=>true,waitLock(){},releaseLock(){}});b.c.Utilities.sleep=()=>{};b.c.Utilities.formatDate=(d,tz,fmt)=>{const p=require('../connector/normalize.cjs').dateParts(d.getTime(),tz);return fmt==='yyyy-MM-dd'?p.date:p.time;};vm.runInContext(fs.readFileSync('apps-script/TimeTreeSync.gs','utf8'),b.c);b.c.UrlFetchApp={fetch(url,options){let json,code=200;if(url.endsWith('/signin')){assert.equal(options.method,'put');json={};}else if(url.includes('/calendars?'))json={calendars:[{id:63108444,name:'Scheduling Calender',alias_code:'test'},{id:96534365,name:'Service and Repair',alias_code:'test2'}]};else if(url.includes('/63108444/'))json={events:[event().raw],chunk:false,since:1};else if(failSecond){json={};code=503;}else json={events:[event({uuid:'second',calendar_id:96534365}).raw],chunk:false,since:1};return {getResponseCode:()=>code,getContentText:()=>JSON.stringify(json),getAllHeaders:()=>({'Set-Cookie':['session=fixture; Secure; HttpOnly']})};}};return b;}
test('native scheduled sync archives before mirroring and unchanged runs do not duplicate archives or history',()=>{const b=nativeBackend();assert.equal(b.c.timeTreeSyncScheduled().changed,2);assert.equal(b.sheets.get('TimeTreeSourceArchive').rows.length,3);assert.equal(b.sheets.get('TimeTreeHistory').rows.length,3);assert.equal(b.c.timeTreeSyncScheduled().changed,0);assert.equal(b.sheets.get('TimeTreeSourceArchive').rows.length,3);assert.equal(b.sheets.get('TimeTreeHistory').rows.length,3);});
test('native timer refuses partial calendar reads and preserves already mirrored bookings',()=>{const b=nativeBackend(true);b.import([event()]);assert.throws(()=>b.c.timeTreeSyncScheduled(),/HTTP 503/);assert.equal(b.sheets.get('TimeTreeEvents').rows.length,2);assert.ok(!b.sheets.has('TimeTreeSourceArchive'));assert.match(b.c.PropertiesService.getScriptProperties().getProperty('TIMETREE_LAST_RUN_STATUS'),/ERROR/);});
if(process.env.TIMETREE_TEST_SNAPSHOT)test('complete private source snapshot survives actual mirror/history functions and retry',()=>{const {buildEvents}=require('../connector/sync.cjs'),events=buildEvents(JSON.parse(fs.readFileSync(process.env.TIMETREE_TEST_SNAPSHOT,'utf8'))),b=backend(),ss=b.c.SpreadsheetApp.getActiveSpreadsheet(),insert=ss.insertSheet;ss.insertSheet=n=>{const s=insert(n);s.getMaxRows=()=>1000000;return s;};assert.equal(b.c.timeTreeApply_(events,'private-dry-run').changed,events.length);assert.equal(b.c.timeTreeApply_(events,'private-retry').changed,0);assert.equal(b.sheets.get('TimeTreeEvents').rows.length,events.length+1);assert.equal(b.sheets.get('TimeTreeHistory').rows.length,events.length+1);for(const e of events){const r=b.sheets.get('TimeTreeEvents').rows.find(r=>r[0]===e.id);assert.deepEqual(JSON.parse(r[3]).raw,e.raw);}console.log('All '+events.length+' source records preserved in memory; no remote writes.');});
test('tag policy enforces company separation and person labels independently of attendees',()=>{
 const b=backend();b.sheets.get('Users').rows.find(r=>r[0]==='worker')[1]='Jacobus';
 const types=['Flagship Electric ','Jacobus','Andre','Allaistair - Kai','Freddie / Andre','Birthday\'s'];
 b.import(types.map((tag,i)=>({...event({uuid:'tag-'+i,attendees:[]}),jobType:tag})));
 assert.deepEqual(Array.from(b.get({action:'calendar'},'worker').events,e=>e.jobType),types.slice(0,2));
 assert.deepEqual(Array.from(b.get({action:'hiCalendar'}).events,e=>e.jobType),types.slice(2,5));
 assert.equal(b.get({action:'hiCalendar'},'worker').events.length,0);
 b.sheets.get('Users').rows.find(r=>r[0]==='worker')[1]='Andre';
 assert.deepEqual(Array.from(b.get({action:'hiCalendar'},'worker').events,e=>e.jobType),['Andre','Freddie / Andre']);
 assert.equal(b.sheets.get('TimeTreeEvents').rows.length,7);
});
test('day opens its own occurrences and links directly to the original TimeTree booking',()=>{
 const view=require('../timetree-calendar.js');const a=event({uuid:'a'}),b=event({uuid:'b',start_at:Date.parse('2026-10-08T06:00:00Z'),end_at:Date.parse('2026-10-08T07:00:00Z')});
 const html=view.layout([a,b],new Date(2026,9,7),'day','data-cal-open','2026-10-07').html;
 assert.match(html,/data-cal-open="tt:63108444:a"/);assert.ok(!html.includes('data-cal-open="tt:63108444:b"'));assert.match(html,/href="https:\/\/timetreeapp.com\/calendars\/test\/events\/a"/);
 assert.ok(view.visible({...a,jobType:' Flagship Electric  '},'Flagship Solar',{role:'Worker',name:'Jacobus'}));
 assert.ok(!view.visible({...a,jobType:'Andre'},'Flagship Solar',{role:'Admin'}));
 assert.ok(view.visible({...a,jobType:'Freddie  /  André'},'Hi Service',{role:'Worker',name:'Andre'}));
 assert.ok(view.visible({...a,jobType:'Allaistair - Kai'},'Hi Service',{role:'Worker',name:'Kia'}));
 assert.ok(!view.visible({...a,jobType:'Freddie'},'Hi Service',{role:'Admin'}));
});
